### ISSUE TITLE
Consider adding automatic installer 

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-documentation#10]
Instructions for automated app installation can be added if we want. This allows for unattended retrieval of files. After installation, I deleted the deployed apps and re-ran the app installation with the installer. Everything tested ok.

The commands to install apps are:

```
cd ~/ood/src
wget https://raw.githubusercontent.com/OSC/ood-apps-installer/master/Rakefile
scl enable rh-ruby22 git19 nodejs010 -- rake
sudo scl enable rh-ruby22 -- rake install
```

Once https://github.com/OSC/ood-apps-installer/issues/1 is implemented we won't need to worry about sync'ing the version numbers to the Rakefile either, so the same script can be used for updating.

**Comment by nickjer** [comment]
I will hold off on adding documentation for this until `ood-apps-installer`:

- [ ] gets full documentation on usage added
- [ ] gets a proper release
- [ ] gets approval from @brianmcmichael and @ericfranz

**Comment by brianmcmichael** [comment]
`ood-apps-installer` has been released and documented
