### ISSUE TITLE
smallish doc fixes

### ISSUE THREAD

**Issue by michaelkarlcoleman** [OSC/ood-documentation#105]
Here are a few minor doc fixes.  (Apologies if some of these already fixed.)

On [this page](https://osc.github.io/ood-documentation/master/installation/resource-manager/slurm.html), the "Note" references "cluster1".  This is apparently supposed to match the "my_cluster" name above.

On [this page](https://osc.github.io/ood-documentation/master/app-development/tutorials-interactive-apps/add-jupyter/copy-app.html), it mentions doing a `git init`.  This fails because there is already a `.git` directory present.  I think I recall the "clone" button also said something about removing existing git history.  It's not clear what the correct resolution here is, but if an absolutely pristine git repo is desired, `.git` should be removed completely.

 In item 7 on the same page, it mentions clicking the "Launch" button.  First specify that the user needs to hit the "Back" button.  There is no "Launch" button on the details page.

**Comment by ericfranz** [comment]
Please reopen if your concerns have not been addressed and thank you for the input!
