### ISSUE TITLE
Add documentation to README on setting up "dev environment" for editing and building documentation

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#12]
For example, what version of Sphinx, and what plugins are required? Example of using Docker to set this up for you. Etc.

**Comment by ericfranz** [comment]
We discussed offline about options including:

1. using puppet to build and deploy our documentation at another location
2. use readthedocs

We should look at keeping it in GitHub pages or on readthedocs. The reason is because this is an open source project and its supposed to be easy to contribute to. This also means that long term, a docker file is not ideal.

readthedocs has (or may soon have) support for plantuml: https://github.com/rtfd/readthedocs.org/issues/407

We could try using the wiag service user account for this purpose. Unfortunately, it will still be tied to a single username/email at OSC.

**Comment by ericfranz** [comment]
Another option is we follow the example of http://singularity.lbl.gov/:

1. They use jekyll, not sphinx
2. They use circle ci to auto test and generate a "build artifact", presumably a build of the site stored on AWS that can be accessed temporarily for testing purposes
3. When merging into production, GitHub auto-builds because they are using jekyll

We could adopt some or all of these ideas.

**Comment by nickjer** [comment]
This is now included in the "Development" section of the `README.md`.
