### ISSUE TITLE
Add section to documentation for Known Issues and Limitations

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#13]
Following an example for inspriation: https://community.box.com/t5/Managing-Your-Content/Box-Notes-Notices-and-Known-Limitations/ta-p/340

Are there others?

We would call out important issues and limitations:

1. Browsers supported (across all apps)
2. Lack of support for Job Arrays
3. Current issue with cat-ing very large files in the shell app

**Comment by basilgohar** [comment]
@ericfranz I think your list there captures the kind of points we'd want to include with regards to issues and limitations.  But I think it's also part of our release notes for this version (like what @nickjer already sent out to the proj list).  But, thumbs up from me on making a spot in the right place in the docs (associated with the appropriate versions).

**Comment by nickjer** [comment]
Another topic to include here is the Safari + Basic auth + websocket issue.

**Comment by ericfranz** [comment]
Dup of https://github.com/OSC/ood-documentation/issues/130
