### ISSUE TITLE
Systemd warning for httpd24 overrides should have path

### ISSUE THREAD

**Issue by treydock** [OSC/ood-documentation#16]
To my knowledge the overriding of systemd is not common knowledge and finding out how do to do the overrides is somewhat painful and may change based on OS.  For CentOS / RedHat it may be worth telling people to drop the override contents into a ```.conf``` file in ```/etc/systemd/system/httpd24-httpd.service.d```.

**Comment by nickjer** [comment]
Sorry for the super late response to this issue, only just now noticed it.

I can add a snippet about manually modifying the conf file in the step 3 RHEL7 directions here:

https://osc.github.io/ood-documentation/installation/software-requirements.html
