### ISSUE TITLE
Add build from source for Ubuntu

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#172]
A few challenges include:

* installing Passenger from their rpm instead of our modified, and installing other dependencies like Ruby and Node.js without SCLs
* possibly modifying configuration of OnDemand (perhaps with the override /etc/ood/nginx_stage.yml) to look for the log files etc. in the correct location (/var/log/nginx instead of /var/log/ondemand-nginx)?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737363369697) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Note that if software collections is not available, the command scl_source should not exist, and then https://github.com/OSC/ondemand/blob/a5ca4e55fb83ae795473f4a8fec8eb4fb34d11a9/nginx_stage/etc/profile will not do anything. Except we might not want this to set SCL_PKGS env var, so will need to test and confirm whether that ends up being set in the PUN and if there are any ramifications for that.

**Comment by johrstrom** [comment]
Building from source directions are left to the reader now.
