### ISSUE TITLE
OnDemand with VM Infrastructure?

### ISSUE THREAD

**Issue by vsoch** [OSC/ood-documentation#179]
Hey On Demand! We have a question on Ask Cyberinfrastructure https://ask.cyberinfrastructure.org/t/open-ondemand-with-vm-infrastructure/921 that I think (hope) you might have the answer for? The user is interested in examples for "VM Infrastructure." I pointed him to your ood-images, and ood-images-full, but I think he's looking for how this connects with a larger application.

If you can, it would be really great if you might be able to comment on AskCI! Let me know if I can help.

**Comment by johrstrom** [comment]
I'm closing this because it looks like @ericfranz answered the question and BJ Lougee (almightybeeij) had already come up with a solution. 

That said, it does seem like we have a few interested parties in VM scheduling, just very little work into making it happen.

**Comment by ericfranz** [comment]
Just to mention, part of the new OnDemand 2 project is to add support to doing interactive work in environments without a batch scheduler. This includes things like fork, ssh, Kubernetes, and cloud VM environments like AWS, OpenStack, Google Cloud, etc.

**Comment by ericfranz** [comment]
https://discourse.osc.edu/t/ondemand-2-x-roadmap-scalability-goals/294

**Comment by vsoch** [comment]
Oh neat! If there is anything I can do to help, I’m game! I made a small development Docker compose application https://www.github.com/vsoch/ood-compose but it does include a scheduler.

**Comment by ericfranz** [comment]
@vsoch definitely, I will keep you posted. https://github.com/vsoch/ood-compose looks awesome. Would you be okay with us sharing a link to this on our documentation?

**Comment by vsoch** [comment]
Yes of course! And I'd be happy to address any issues that come up, and help other developers / users with customization they might want.
