### ISSUE TITLE
Look into supporting multiple versions of documentation

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-documentation#19]
This is possible with https://robpol86.github.io/sphinxcontrib-versioning/index.html

**Comment by nickjer** [comment]
Seems it is not compatible with the latest Sphinx as documented here https://github.com/Robpol86/sphinxcontrib-versioning/issues/39

**Comment by nickjer** [comment]
Another option would be to build the different versions of the documentation in sub-directories of `docs/`.

- `docs/latest/...`
- `docs/v1.0.0/...`

Similar to:

- http://guides.rubyonrails.org/v4.1/
- http://guides.rubyonrails.org/v4.2/
- http://guides.rubyonrails.org/v5.0/

**Comment by nickjer** [comment]
If we do the above route though, maybe it is best to keep the builds within the branch `gh-pages` and include a build script that builds all the versioned branches.

**Comment by ericfranz** [comment]
I like this idea, following the Rails convention.

**Comment by ericfranz** [comment]
We should also have a /latest/ being a copy of the latest tag i.e. in rails example:

- http://guides.rubyonrails.org/v4.1/
- http://guides.rubyonrails.org/v4.2/
- http://guides.rubyonrails.org/v5.0/
- http://guides.rubyonrails.org/latest/ => same as http://guides.rubyonrails.org/v5.0/
- http://guides.rubyonrails.org/master/ => master branch HEAD
- http://guides.rubyonrails.org/some-branch/ => some-branch HEAD

**Comment by ericfranz** [comment]
With /latest/ we will be able to share this link.

**Comment by nickjer** [comment]
The `/latest/` trick may require human intervention (e.g., creating a redirect in the `/latest/index.html` file to a version of our choosing).

**Comment by ericfranz** [comment]
No symlinks and no redirect. Just cp -r from vX.Y to latest ( or better, rsync to mirror).

Would need routine to determine the latest release branch available and then match that against the current branch

**Comment by nickjer** [comment]
You would have to manually `cp -r` for the first time followed by a git commit and push, and then modify the Travis CI script in master to `rm -fr latest` and `cp -r` again every time that specific branch is modified.

**Comment by ericfranz** [comment]
So the psuedo code is:

```ruby
if CURRENT_BRANCH == LATEST_VERSION
  rm -rf latest if latest.directory_exists?
  cp -r CURRENT_BRANCH latest
end
```

I don't see the manual step.

**Comment by ericfranz** [comment]
I guess you create and push a branch. The manual step is triggering Travis to run the tests on that branch?

**Comment by nickjer** [comment]
Ah, you actually want the code to scan all the branch names and determine the latest version, I misunderstood the first time.

**Comment by nickjer** [comment]
This is now supported after many trial and errors.
