### ISSUE TITLE
noVNC connot connect the server

### ISSUE THREAD

**Issue by flybirdkh** [OSC/ood-documentation#192]
HI,
I got the Desktop applications,but when I use the button of 'launch desktop' it show me 'cannot connect the server'.
the log of ondemnad server:
(mate-panel:666783): dconf-CRITICAL **: 09:16:35.798: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
(mate-panel:666783): dconf-CRITICAL **: 09:16:35.798: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
(mate-panel:666783): dconf-CRITICAL **: 09:16:35.798: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
(mate-panel:666783): dconf-CRITICAL **: 09:16:35.798: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
(mate-panel:666783): dconf-CRITICAL **: 09:16:35.798: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.

and the compute node system's log :
journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
 journal: unable to create directory '/run/user/2738/dconf': Permission denied.  dconf will not work properly.
pulseaudio[667884]: [autospawn] core-util.c: Failed to create secure directory (/run/user/2738/pulse): No such file or directory
pulseaudio[667884]: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
pulseaudio[667884]: [pulseaudio] main.c: Failed to acquire autospawn lock
pulseaudio[669398]: [autospawn] core-util.c: Failed to create secure directory (/run/user/2738/pulse): No such file or directory
pulseaudio[669398]: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
 pulseaudio[669398]: [pulseaudio] main.c: Failed to acquire autospawn lock
 mate-session[666711]: CRITICAL: gsm_systemd_set_session_idle: assertion 'session_path != NULL' failed

How to solve this problem ?

**Comment by flybirdkh** [comment]
The compute node :
mate desktop(default)
TurboVNC(2.2.2)
Websockify(0.8.0)
Nmap (7.70)

**Comment by flybirdkh** [comment]
I use the pulseaudio --start to solve this problem ,but now the log show me this:

(mate-panel:293015): GLib-GObject-CRITICAL **: 16:15:58.095: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
mate-session[292809]: CRITICAL: gsm_systemd_set_session_idle: assertion 'session_path != NULL' failed

**Comment by MorganRodgers** [comment]
@flybirdkh I suspect that you need to export a value for `XDG_RUNTIME_DIR` which was the solution to the Discourse question [Interactive Desktop dconf Error](https://discourse.osc.edu/t/interactive-desktop-dconf-error/347).

In general if you need help troubleshooting an issue please check our Discourse at https://discourse.osc.edu, and if you do not find a solution post a new question there.
