### ISSUE TITLE
OnDemand install failed

### ISSUE THREAD

**Issue by flybirdkh** [OSC/ood-documentation#199]
hi 

when I install OnDemand using 'yum  install ondmand'
it show me this 
![image](https://user-images.githubusercontent.com/53069666/65655364-96961580-e04e-11e9-9c20-ba1d44802e54.png)
and I cannot find ondemand-git

how to solve it

**Comment by flybirdkh** [comment]
it's solved

**Comment by treydock** [comment]
There was a small issue with the repo server and ondemand-git got removed prematurely. I added the package back.

**Comment by flybirdkh** [comment]
thank you ,i've got the package.
