### ISSUE TITLE
Clearer instructions on Apache environment change

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-documentation#2]
This can lead to confusion for sys admins when installing OOD:

![image](https://cloud.githubusercontent.com/assets/4260509/24675865/addadb82-194e-11e7-836b-1e31f41e65eb.png)

It isn't obvious the above is describing how to change a line.

**Comment by nickjer** [comment]
Suggestion by Martin Cuma:

>Do this by editing /opt/rh/httpd24/service-environment and replacing:
> ```
> HTTPD24_HTTPD_SCLS_ENABLED="httpd24"
> ```
> with
> ```
> HTTPD24_HTTPD_SCLS_ENABLED="httpd24 rh-ruby22"
> ```

**Comment by treydock** [comment]
The change is unnecessary.  I never make it on OSC systems.

**Comment by nickjer** [comment]
@treydock: That is because I believe when you installed Puppet at OSC it also installed Ruby on the system. So our Apache proxy is using this older version of Ruby.

But when we install OOD on a fresh RHEL or CentOS system, it seems Ruby doesn't come installed by default. So we piggy-back off of the Software Collections installed Ruby.
