### ISSUE TITLE
Update install from source directions to abstract away the rpm dependencies

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#200]
A diff on these build from source directions and the differences for the Ansible role may help.

The point of many of the rpm dependencies https://osc.github.io/ood-documentation/develop/installation/from-source/system-dependencies.html is to ensure that Passenger and NGINX and Apache all look in the right locations, and the SCL dependencies Ruby and Node with the modification to Apache ensure that the proper Ruby environment is sourced.

The ood_portal_generator config and nginx_stage configs and /etc/ood/profile all contain places where defaults can be modified to handle different locations for these dependencies. Build from source should assume we don't know where the dependencies are coming from (while using the rpms as examples), make note of the paths to each dependency installation, and explicitly set these paths in the proper config files (even though they happen to be defaults).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737316235853) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
instead - we removed the build from source directories.
