### ISSUE TITLE
Update build from source directions for 1.6.17

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#202]
We now depend on system git as of 1.6.17

* https://yum.osc.edu/ondemand/1.6/web/el7/x86_64/ondemand-git-1.6-1.el7.x86_64.rpm 

Remove mention of installing the right git from https://osc.github.io/ood-documentation/develop/installation/from-source/core-apps.html as well

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737421530728) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
These directions have now been removed as per #721.
