### ISSUE TITLE
Add directions on setting up an interactive VNC app with a window manager

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#206]
A separate top level section?

Give two examples, one with MATE one with XFCE - since those are the two desktops we ship support for. The XFCE example is in use at OSC right now https://github.com/OSC/bc_osc_matlab/blob/db4b351d22d47ddf9ecb83a859f044c29b1bf68c/template/script.sh.erb#L11-L26 and https://github.com/OSC/bc_osc_matlab/tree/db4b351d22d47ddf9ecb83a859f044c29b1bf68c/template/config

For MATE, there is marco, but then there are other tools that work with it. For example, you need a panel of some type so when you minimize a window managed by marco you can find the minimized window and maximize it again.

What are the steps for this?

**Comment by ericfranz** [comment]
Based on reading https://wiki.archlinux.org/index.php/MATE and similar documentation, I start marco and mate-panel directly which by default will use DISPLAY=0.

I clone https://github.com/OSC/bc_osc_matlab and then modify template/script.sh.erb:

```diff
 #
 # Launch Xfce Window Manager and Panel
 #

 (
-  export SEND_256_COLORS_TO_REMOTE=1
-  export XDG_CONFIG_HOME="<%= session.staged_root.join("config") %>"
-  export XDG_DATA_HOME="<%= session.staged_root.join("share") %>"
-  export XDG_CACHE_HOME="$(mktemp -d)"
-  module restore
-  set -x
-  xfwm4 --compositor=off --daemon --sm-client-disable
-  xsetroot -solid "#D3D3D3"
-  xfsettingsd --sm-client-disable
-  xfce4-panel --sm-client-disable
+  marco --no-composite --no-force-fullscreen --sm-disable
+  mate-panel
 ) &
```

The result is a panel at the top and MATLAB in a window where I can drag it around, minimize, and maximize.

![matlab_working](https://user-images.githubusercontent.com/512333/68054769-77317e80-fcc5-11e9-893a-073b7c120428.png)

Note, with this bare-bones setup, it doesn't take long playing with MATLAB to produce problems for MATLAB (resize the window, move it around, minimize then maximize)

![matlab_broken](https://user-images.githubusercontent.com/512333/68054778-7ac50580-fcc5-11e9-9efb-b18b8b87da0b.png)

This doesn't seem to be easily reproduceable. Sometimes when I launch I get a window with out the panel, and sometimes its a black screen, so when you minimize the window, you cannot find it to maximize again (because there is no visible panel):

![matlab_nopanel](https://user-images.githubusercontent.com/512333/68055207-7cdb9400-fcc6-11e9-8564-9d18bc0f8733.png)

Might be some state left over in my home directory causing problems? I don't know how MATE works enough to know how to diagnose the problems.

**Comment by MorganRodgers** [comment]
I recall that we were having problems with Matlab when I first started. There might be a record in SNow.

**Comment by ericfranz** [comment]
It happens when you resize the browser window, then you get a bunch of redraw errors.

**Comment by MorganRodgers** [comment]
I found the record: https://www.mathworks.com/matlabcentral/answers/373897-external-monitor-throws-java-exception which I found when researching Incident INC0338283.

Adding `-Dsun.java2d.xrender=false` to `/usr/local/MATLAB/R2018a/bin/glnxa64/java.opts` was the solution that was proposed in the forum, and what we did at OSC. I believe that Heechang added those options somewhere, but SciApp's actions were not captured in the incident so I am not sure where the changes were made, or if they have been undone. This problem has impacted Matlab users outside of OSC, and there does not seem to be an official answer:

- https://www.mathworks.com/matlabcentral/answers/424725-disable-xrender-at-startup
- https://www.mathworks.com/matlabcentral/answers/381324-why-do-i-get-java-exception-on-display-change

Matlab's Java options can be set at startup using a `java.opts` file, and the first place that Matlab checks for that file is `pwd`. For OSC OnDemand we explicitly `cd` from the BatchConnect session directory to `$HOME`, so `$HOME/java.opts` would be the correct location.

**Comment by MorganRodgers** [comment]
With the following I reliably get a `mate-panel`, no Java errors, and everything exits when the Matlab process ends.

```diff
# Set working directory to home directory
cd "${HOME}"

+ # Fix the Java errors relating to resizing the window
+ cat << JAVA_OPT > java.opts
+ -Dsun.java2d.xrender=false
+ JAVA_OPT

 #
- # Launch Xfce Window Manager and Panel
+ # Launch Mate Window Manager and Panel
 #

- (
-  export SEND_256_COLORS_TO_REMOTE=1
-  export XDG_CONFIG_HOME="<%= session.staged_root.join("config") %>"
-  export XDG_DATA_HOME="<%= session.staged_root.join("share") %>"
-  export XDG_CACHE_HOME="$(mktemp -d)"
-  module restore
-  set -x
-  xfwm4 --compositor=off --daemon --sm-client-disable
-  xsetroot -solid "#D3D3D3"
-  xfsettingsd --sm-client-disable
-  xfce4-panel --sm-client-disable
-  marco --no-composite --no-force-fullscreen --sm-disable
-  mate-panel
- ) &

+ # no need to run a subshell
+ marco --no-composite --no-force-fullscreen --sm-disable &
+ # mate-panel blocks, but does not work reliably when launched in the same subshell as marco
+ mate-panel &

#
# Start MATLAB
#
```

**Comment by ericfranz** [comment]
Is `java.opts` a MATLAB specific thing?

**Comment by MorganRodgers** [comment]
This is where MathWorks describes using a `java.opts` file: https://www.mathworks.com/help/matlab/matlab_env/java-opts-file.html. I do not know enough desktop Java applications to know if the `java.opts` file for Matlab will collide with other apps.

Related: entering the following command can be used to confirm what Java options are active in Matlab: `java.lang.management.ManagementFactory.getRuntimeMXBean.getInputArguments`.

**Comment by treydock** [comment]
`java.opts` is not Matlab specific. I've used it with other Java applications in the past.

**Comment by MorganRodgers** [comment]
So what's our best practice here? Append to file (conditionally, skipping if argument already exists), backup existing files?

I am not aware of an environment variable that lets us specify a custom path other than `$PWD`. The other risk with the `java.opts` approach is that sites (OSC for example) use that file to specify Java memory limits, and I think that the first `java.opts` file found wins.

**Comment by johrstrom** [comment]
What you have there is fine (I can't speak to the removals).  I think `java.opts` is just a conventional *name* for options files. The program itself has find it and read it and so on (maybe even the shell that boots it?).  It's not like a JVM thing to go searching for it, folks have to program for it and calling your options file `java.opts` is just something more than one project has done.

Which is to say no other java programs should be looking for `~/ondemand/data/sys/dashboard/batch_connect/sys/bc_osc_matlab/output/$UUID/java.opts`

> I think that the first java.opts file found wins.

It's probably last property defined wins given some are global (in matlabroot/bin/arch) and this file is user specific.
