### ISSUE TITLE
Clarify SELinux availability

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-documentation#208]
While we have SELinux RPMs available they are not in the public channel yet. The docs need to be updated to point to both the latest repo for the brave, and also to inform more cautious adopters that we expect SELinux to be publicly available in the 1.7.x release.

For anyone stumbling across this issue you can find the SELinux RPMs at a URL like the following:

https://yum.osc.edu/ondemand/latest/web/el7/x86_64/ondemand-selinux-1.6.20-1.el7.x86_64.rpm

**Comment by treydock** [comment]
To help UC I put `ondemand-selinux` for latest 1.6 in public repos: https://yum.osc.edu/ondemand/1.6/web/el7/x86_64/ondemand-selinux-1.6.20-1.el7.x86_64.rpm

I did this because latest docs do mention installing `ondemand-selinux` and I didn't want to force sites to use `latest` repo.
