### ISSUE TITLE
Make configuring "Logout" url more prominent

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#216]
The default logout is made for basic auth and is configurable to other URLs but is hidden here: https://osc.github.io/ood-documentation/master/infrastructure/ood-portal-generator/configuration.html#configure-logout-redirect

This and other authentication related configuration (using the ood-portal-generator) should be moved to INSTALL > Authentication. In the case of Logout, it should be step 3 in the overview i.e.

1. Configure Apache Authentication
2. Setup User Mapping
3. **Configure Logout**

https://osc.github.io/ood-documentation/master/authentication/overview.html

**Comment by treydock** [comment]
Should the docs for other ood-portal-generator things be moved out of legacy section too? The first link is under legacy docs section it seems.

**Comment by ericfranz** [comment]
Yes I'll Open a separate issue for moving remaining items out of legacy section
