### ISSUE TITLE
Move relevant legacy docs to more prominenant locations in documentation

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#231]
For example see https://osc.github.io/ood-documentation-test/logout/infrastructure/ood-portal-generator.html

Some of these we already address in the documentation, such as the Example Configurations section, though reviewing each to verify all the important information is in the other spots should be done.

**Comment by ericfranz** [comment]
#216 did this for logout

**Comment by johrstrom** [comment]
I'm going to pick this up and work on it a bit.  I feel like we need a `reference` section where most of this stuff can live.  

The section would be a reference point for config files (like `ood_portal.yml` that we already have docs for) and all the things you can put in a `submit.yml.erb` (that we don't yet have in full).

I think success for this ticket would be:
* move this stuff to a reference
* Going though all these files and removing all the things that are documented elsewhere
* generating smaller tickets for 'move this here'

Then we can add reference documentation so users can see all the options available to them (and have cheat sheets for common yml formatting errors! :laughing: ) and by going through it all we'll have identified all the items that could move out of this section.

**Comment by ericfranz** [comment]
A lot of the stuff in legacy docs is no longer relevant though, so pick wisely.
