### ISSUE TITLE
Can't install OnDemand on RedHat7 Workstation

### ISSUE THREAD

**Issue by cloudliu01** [OSC/ood-documentation#242]
When I tried to install it on a RHEL7 Workstation it gave me error below:
> sudo yum install ondemand
https://yum.osc.edu/ondemand/1.6/web/el7Workstation/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
...

Could someone help build a RHEL7 Workstation version please?

Thanks
Cloud

**Comment by treydock** [comment]
Open `/etc/yum.repos.d/ondemand-web.repo` and replace `$releasever` with just `7`.

**Comment by cloudliu01** [comment]
Yes, the issue got resolved by the way you advised.

Thanks for the quick reply!
