### ISSUE TITLE
document OOD_BC_SSH_TO_COMPUTE_NODE

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#252]
A feature was added from the discourse issue below. This ticket is to document that feature flag (that toggles the 'ssh to compute node' button in an interactive apps' card).

https://discourse.osc.edu/t/removing-ssh-connection-button-on-interactive-apps/578

**Comment by treydock** [comment]
This appears to already be documented: https://github.com/OSC/ood-documentation/blob/develop/source/customization.rst#disable-host-link-in-batch-connect-session-card
