### ISSUE TITLE
OOD PR Merge pull request #502 from OSC/feature/nginx_max_upload_size

### ISSUE THREAD

**Issue by oscwiag** [OSC/ood-documentation#281]
Create documentation for https://github.com/OSC/ondemand/commit/961f5af53c8e0f54c1bb7db4e53802f888041f28

**Comment by johrstrom** [comment]
I picked this up in this commit. Let me know if there's anything missing.

https://github.com/OSC/ood-documentation/pull/364/commits/d9a23e97a7b1dcbecdaeb77ee0ac2d477f74f73a
