### ISSUE TITLE
Update service command for RHEL7

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-documentation#3]
Although running:

```sh
sudo service httpd24-httpd restart
```

works for RHEL7, that above command is becoming deprecated.

Instead we should use:

```sh
sudo systemctl restart httpd24-httpd
```

@brianmcmichael should confirm the above command is correct when he reinstalls OOD on our test RHEL7 server.

**Comment by brianmcmichael** [comment]
Did not receive any output when calling the command.

**Comment by brianmcmichael** [comment]
This command also appears in:

 - [ ] 10.6 update restart command
 - [ ] 11.6 update restart command

Replacing the `service` commands with the `systemctl` equivalents worked without issue on RHEL7
