### ISSUE TITLE
Add list of all component versions for a release in release-1.0

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#33]
In the release notes we do not list anywhere the versions of all the components during the release.

The only way to find out is to look at https://github.com/OSC/ood-apps-installer/blob/master/config.json and/or the latest versions of the components.

The negative of this is that every time we update https://github.com/OSC/ood-apps-installer/blob/master/config.json for patch releases of apps we would need to update this list too.

**Comment by nickjer** [comment]
We would only update it if the `ood-apps-installer` was updated, which doesn't occur that often.

Note, for tables in rest documents I'd recommend either [CSV Table](http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4) or [List Table](http://docutils.sourceforge.net/docs/ref/rst/directives.html#list-table) for their simplicity.
