### ISSUE TITLE
OOD PR Support host wildcards in Shell app (#601)

### ISSUE THREAD

**Issue by oscwiag** [OSC/ood-documentation#332]
Create documentation for https://github.com/OSC/ondemand/commit/e45aba5ba589ffb6c115a770274a10999ec87a88

**Comment by msquee** [comment]
Closed by https://github.com/OSC/ood-documentation/commit/819f627cd28ef9e20d5e4a882e48655f447bda3f

**Comment by johrstrom** [comment]
I think you mean https://github.com/OSC/ood-documentation/pull/364/commits/661fb35c039af5a312a012a62471d4a144db7640#diff-d3f03272989f7139cb71ac186b54adc6R289-R298 ?

Either way I think we should keep these open until they merge into the release branch.
