### ISSUE TITLE
Build from source directions are out of date

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#404]
Build from source is for 1.6. We need directions for 1.8. Might also consider fixing 1.7 build directions on the 1.7 branch.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202437557935160) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
In particular "Install OnDemand Infrastructure" and Install OnDemand Core Applications" should just be merged into "Install OnDemand" and use the monorepo. Can consult the rpm spec file in the root of OnDemand to see specific steps we might need to do. One thing that would be nice would be to install gems system wide though each app could have its gem dependencies installed in the app directories. I think we would provide directions for each path and let them decide. The npm dependencies of course get installed in the app root directories.

**Comment by ericfranz** [comment]
And of course https://osc.github.io/ood-documentation/latest/installation/from-source/system-dependencies.html needs fixed.

**Comment by ericfranz** [comment]
This is out of date:

https://osc.github.io/ood-documentation/develop/installation/from-source/core-apps.html

>OnDemand’s core applications are stored in their own Github repositories and should each be cloned to /var/www/ood/apps/sys/$APP:
>
>        ood-activejobs: /var/www/ood/apps/sys/activejobs
>        ood-dashboard: /var/www/ood/apps/sys/dashboard
>        ood-fileeditor: /var/www/ood/apps/sys/file-editor
>        ood-fileexplorer: /var/www/ood/apps/sys/files
>        ood-myjobs : /var/www/ood/apps/sys/myjobs
>        ood-shell: /var/www/ood/apps/sys/shell

**Comment by Oglopf** [comment]
These directions have now been removed as per #721.
