### ISSUE TITLE
Breaking changes: Ruby SCL is no longer loaded by default by Apache

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#510]
It might have been mentioned but maybe more explicitly that the Ruby SCL is no longer loaded by default by Apache, since we are no longer using the ruby mapping script by default. So if sites want to switch to 1.8 functionality they need to take several more steps than before
 
We might instruct them to ask on Discourse if they want to revert to the 1.8 functionality and only provide directions at that time.

**Comment by johrstrom** [comment]
I said in the RNs to use a wrapper script. I think that's the most sustainable route for them, than editing files that get rewritten by RPMs.
