### ISSUE TITLE
Breaking changes: explain in greater detail what types of limitations the lua string matching has

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#511]
We need to explain the limitations of Ruby string matching, also that the system Ruby (2.0) may be sufficient for the regex mapping necessary (though I think our mapping script from 1.8 would need to be modified to work with 2.0, I do not remember), and that even a bash command can be used that may be faster if the new lua string match strategy is not sufficient.

**Comment by johrstrom** [comment]
> the limitations of Ruby string matching

I'm not sure _I_ know what these are. Do you mean limitations caused by dependencies or actual functionality provided by Ruby's `Regexp` library?

**Comment by treydock** [comment]
http://lua-users.org/wiki/PatternsTutorial#:~:text=Limitations%20of%20Lua%20patterns&text=Unfortunately%20Lua%20patterns%20do%20not,or%20use%20LPeg%20%5B3%5D.

It's limitations in type of regex that Lua supports compared to Ruby.

**Comment by johrstrom** [comment]
Thanks. Apparently it's a mistype. Should read "limitations of lua string matching" not "Ruby string matching"
