### ISSUE TITLE
K8s docs for Kyverno policies

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#560]
Ticket to create documentation for Kyverno policies we use in Kuberenetes clusters.

**Comment by treydock** [comment]
Is it okay to just link to Github where we store them? The policies we use come from 2 places:

https://github.com/kyverno/kyverno/tree/main/charts/kyverno-policies/templates
https://github.com/OSC/osc-helm-charts/tree/main/charts/kyverno-policies/templates

The OSC link are more specific to OnDemand usage and other things we do unique at OSC.  The Kyverno repo policies are just general purpose best-practice security policies.

**Comment by johrstrom** [comment]
We don't need to go into great detail. I think just describing the dependencies like LDAP and how those tie into the `[group|user]-validation` policies we have.

Really I think we just need to communicate this is how we're enforcing security, and these are the dependencies you'd need to get a similar setup.  A paragraph or two would be fine, with the links the reader has a lot of work outside of these docs ahead of them either way.
