### ISSUE TITLE
2. Modify System Security - iptables

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-documentation#6]
This page was updated after I ran through the latest run.

In doing so, the `iptables` commands were removed and replaced with a link to the CentOS documentation.

While it's probably appropriate that we send people to documentation, removing the quick and easy instructions make this step a bottleneck in the install procedure and increase the complexity of the install.

I'd recommend that we keep the existing `iptables` commands (since `firewalld` also uses these commands) as an example, and then leave it up to the user whether they want to perform them verbatim or use something more secure.

Many of the installations at this point are going to be for evaluations, so we want to streamline this process and get people up and running.

**Comment by nickjer** [comment]
You pointed out that the last command we supplied broke for RHEL 7, so it was already incorrect.

My opinions below:

- Maintaining documentation that works across RHEL6, CentOS6, RHEL7, CentOS7 and the various firewall tools for opening ports 80/443 that *should* be second nature to a good sys admin puts an unnecessary burden on us
- We currently don't document how (but we mention these need to be done):
  - set up host name with machine's ip address
  - generate SSL certificate
  - disable SELinux
  - setup LDAP/NSS
  - mount shared file system
- We can ask Trey to enable ports 80/443 in his Puppet script when spinning up blank OOD portal VM's, then this won't be a burden on us when testing installs
- So far no installation site has asked us about setting up the firewall rules

**Comment by treydock** [comment]
My 2-cents.  Document the ports that need to be opened and leave it up to sysadmin to figure out how.  The way people open ports probably varies from site to site.

**Comment by nickjer** [comment]
I removed the documentation on walking the user through iptables.
