### ISSUE TITLE
add ssl support should have additional steps for dex users

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#661]
add ssl support page - below - should have additional steps for dex users because we get a lot of discourse topics regarding dex and certificate issues, namely the CA not being trusted.

https://github.com/OSC/ood-documentation/blob/develop/source/installation/add-ssl.rst

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202000120618197) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
It needs to be clear that the step of adding SSL to truststore is only needed if the chain is not already trusted.  For example, when I tested Dex and SSL with OSC when we used InCommon certs, the truststore was fine and no changes were needed.
