### ISSUE TITLE
Remove PAM authentication

### ISSUE THREAD

**Issue by treydock** [OSC/ood-documentation#682]
@johrstrom I wonder if we should remove the PAM authentication section? It relies on `AuthType Basic` which is incredibly insecure, for example it stores the user's password in their browser only base64 encoded so if someone hacks a personal computer, they could easily pull out that user's password.  The various PAM modules you might use like SSSD can all be done other ways like LDAP or AD through Dex or Keycloak.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202309051006096) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yea, but let's keep the page saying something to the same affect and that it's left to the reader to try if they want.
