### ISSUE TITLE
7. Add cluster configuration files

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-documentation#7]
This is more of a question than an issue, but I noticed that the configuration files we are using on step 7 are `v1`, I know `v2` is available now.

Per @nickjer we're not using `v1` on OOD yet, so I'm not sure what the difference is and when we're making the cutover.

**Comment by nickjer** [comment]
We will cut over to `v2` when all the system apps support `ood_core` and these versions become part of the default OOD install.

Note: `ood_core` is semi-backwards compatible with `v1`. So it will work with the documented OOD install cluster config `v1` file and Torque.
