### ISSUE TITLE
Update brand to match website

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#70]
MVP is to add logo, link to website, and use OH-TECH colors (red or the OH-TECH grey or the "jazzy" background that communications suggested - I'll share that in an email to WIAG.

Also, keep in sync loosely with https://github.com/OSC/Open-OnDemand/issues/27

**Comment by nickjer** [comment]
Not sure how to easily override the colors in the sphinx_rtd_theme.
