### ISSUE TITLE
build ondemand-dex from source instructions don't work for me

### ISSUE THREAD

**Issue by simonLeary42** [OSC/ood-documentation#701]
https://osc.github.io/ood-documentation/latest/authentication/dex.html#installing-ondemand-dex-from-source
It says that it requires go 1.14.x, but I think it actually requires 1.16.x

Using ubuntu 20.04, I got the same errors reported [here](https://stackoverflow.com/questions/68752103/package-io-fs-is-not-in-goroot-while-building-the-go-project) and using go 16 made the error go away.

But then, `make` seems to be a success but no bin/ directory has been created. `make` puts nothing to stdout, but here's `make --debug`:

```
root@ood-head:~/go/src/github.com/dexidp/dex#  ls
ADOPTERS.md  MAINTAINERS  api              config.docker.yaml  docker-compose.override.yaml.dist  docs        flake.nix  pkg      storage
Dockerfile   Makefile     cmd              config.yaml.dist    docker-compose.test.yaml           examples    go.mod     scripts  web
LICENSE      README.md    config.dev.yaml  connector           docker-compose.yaml                flake.lock  go.sum     server
root@ood-head:~/go/src/github.com/dexidp/dex# make --debug
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'generate' does not exist.
Must remake target 'generate'.
Successfully remade target file 'generate'.
root@ood-head:~/go/src/github.com/dexidp/dex# ls
ADOPTERS.md  MAINTAINERS  api              config.docker.yaml  docker-compose.override.yaml.dist  docs        flake.nix  pkg      storage
Dockerfile   Makefile     cmd              config.yaml.dist    docker-compose.test.yaml           examples    go.mod     scripts  web
LICENSE      README.md    config.dev.yaml  connector           docker-compose.yaml                flake.lock  go.sum     server
root@ood-head:~/go/src/github.com/dexidp/dex# 

```

Am I doing something wrong?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671691370104) by [Unito](https://www.unito.io)

**Comment by simonLeary42** [comment]
It says to use `make` but it needs `make build`

**Comment by simonLeary42** [comment]
https://github.com/OSC/ood-documentation/pull/702

**Comment by treydock** [comment]
I posted on ondemand-dex repo but can post here too, there are Ubuntu 20.04 packages for ondemand-dex: https://apt.osc.edu/ondemand/latest/web/apt/pool/focal/

There are no OnDemand 2.0 packages yet for Ubuntu 20.04 but there will be in near future.  For now could download deb file directly and install since right now no 2.0 repos I'd recommend adding to your system for Ubuntu.

**Comment by simonLeary42** [comment]
Thanks. Where on that repo did you post it? I was looking earlier but found nothing.

**Comment by treydock** [comment]
The issue you opened on the ondemand-dex repo: https://github.com/OSC/ondemand-dex/issues/24#issuecomment-1190872937

**Comment by treydock** [comment]
I'm going to go ahead and close this.  Very soon there will be Ubuntu packages for OnDemand 2.0 for both 18.04 and 20.04.  There will be no need to do things from source.
