### ISSUE TITLE
install ondemand-dex from source where is config file?

### ISSUE THREAD

**Issue by simonLeary42** [OSC/ood-documentation#704]
https://osc.github.io/ood-documentation/latest/authentication/dex.html#installing-ondemand-dex-from-source

The guide has me install 

* /usr/sbin/ondemand-dex
* /etc/systemd/system/ondemand-dex.service
and nothing else.

It says right below that guide that 
> The default location for Dex configurations is `/etc/ood/dex/config.yaml`

But it doesn't tell me what to write in such a file.
When I start the service, It says file not found.
I thought maybe it could use the dex: config that I put in ood_portal.conf, but it can't.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671625902931) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
The configuration of Dex is the same if you install from package or from source: https://osc.github.io/ood-documentation/latest/authentication/dex.html#configuring-ondemand-dex

**Comment by treydock** [comment]
Going to close, soon OnDemand 2.0 will have Ubuntu 20.04 and 18.04 packages.
