### ISSUE TITLE
Warn about using "partition" on custom user defined attributes in the User Form

### ISSUE THREAD

**Issue by i-mtz** [OSC/ood-documentation#707]
For SLURM users it might make sense to define `partition`  as a session context attribute, but this will lead to the variable set not properly passed to the script due to `partition` being a method of the Ruby mixin [enumerable](https://ruby-doc.org/core-2.6.1/Enumerable.html#method-i-partition) 

Adding a warning on that section might help other users. 

Against which branch should a PR be submitted in this case? The section `source/app-development/interactive/form.rst` is not present on the `development` branch?

**Comment by johrstrom** [comment]
Go ahead and submit to latest. There's a bug ticket upstream and we'd like to fix it for 2.1 (which is what the develop docs describe).
