### ISSUE TITLE
docs for vnc_container

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#723]
https://github.com/OSC/ood_core/pull/774 is not yet merged, but it will be shortly and while it's on my mind and I have it here, let's document this template.

Here's the `mate.def` I've been working with which should likely be documented as well.

```singularity
Bootstrap: docker

From: centos:7

%environment
    PATH=/opt/TurboVNC/bin:$PATH

%post   
    yum install -y epel-release
    yum groupinstall -y 'MATE Desktop'
    yum install -y python3-pip
    pip3 install ts
    yum install -y https://yum.osc.edu/ondemand/latest/compute/el7Server/x86_64/python-websockify-0.8.0-1.el7.noarch.rpm
    yum install -y https://yum.osc.edu/ondemand/latest/compute/el7Server/x86_64/turbovnc-2.2.3-1.el7.x86_64.rpm
    yum remove -y tigervnc-server python3-pip mate-power-manager
    yum clean all
    rm -rf /var/cache/yum/*
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202933063872046) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
For EL8 you just do `dnf install mate-desktop`.  Also be good to install the websockify package from latest repo too to avoid ancient 1.6 repo.

**Comment by johrstrom** [comment]
Yea I just had the centos:7 stuff on hand. But yea, docs should likely show both.

**Comment by georgiastuart** [comment]
It should definitely be documented that the container needs websockify and turbovnc installed at a minimum.
