### ISSUE TITLE
[release_2.0] Upgrade to NodeJS 14

### ISSUE THREAD

**Issue by oscwiag** [OSC/ood-documentation#729]
Create documentation for https://github.com/OSC/ondemand/pull/2316

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203119095508423) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Moving question to more appropriate place:

@johrstrom How should this get documented? Do we just update 2.0 release notes ? That only has RHEL7/RHEL8 steps. Or do we provide new Upgrade page? Or do we just want to document in the Discourse announcement?
