### ISSUE TITLE
Remove 2.1 related content for SC Doc Release

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ood-documentation#731]
We are looking to release the new documentation at SC this year, but it will be a few months before the `2.1` release of OOD itself. 

This is an epic to track the various parts of the docs that need to be rewritten in order to release the docs in time at SC but not include any instructions from `2.1` that may not be ready yet.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203125306983548) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
Let's try to identify and list the places in the docs this week or next to track what needs pulled.

**Comment by Oglopf** [comment]
After some discussion internally it seems best to just wait for the release in January to release the docs rather than try to pull out what is here and possibly miss things and create more work for ourselves than we already have.
