### ISSUE TITLE
enable reverse proxy documentation confusing

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#732]
enable reverse proxy documentation can be confusing because it's got alot of LDAP info and more. These pages should limit/focus on just the reverse proxy and remove all that other stuff.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203143895672979) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
Looking at the `dev` branch, it looks like that's been done:
https://osc.github.io/ood-documentation/develop/how-tos/app-development/interactive/setup/enable-reverse-proxy.html

**Comment by johrstrom** [comment]
Yes, this was fixed in #665.
