### ISSUE TITLE
Outdated App Sharing Documentation

### ISSUE THREAD

**Issue by abujeda** [OSC/ood-documentation#757]
While updating the documentation for the new configuration features for the pinned apps, I was reviewing the images that have pinned apps. ~~There are 2 in the App Sharing section that need replacing with the pinned apps new look and feel.~~

I was following the instructions in the `Enabling The App Sharing Dashboard `section and they seem to be outdated.
https://osc.github.io/ood-documentation/latest/app-sharing.html?highlight=sharing#enabling-the-app-sharing-dashboard
I could be wrong as I am new to `App Sharing`, but I think the Dashboard homepage no longer displays shared apps.

~~If this section needs updating, could the images be replaced as part of the update?~~

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203701641407541) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
I was able to render Shared Apps using the URL:` /pun/dev/ood/apps/featured`
The `featured` controller uses its own template to render the application tiles, there is no need to update the images.

If the documentation is up to date, this issue can be closed.

**Comment by johrstrom** [comment]
> I was able to render Shared Apps using the URL: /pun/dev/ood/apps/featured

Yes that stuff needs to be removed. `pinned_apps` replaced that.  Sadly there was no release note for the same and I'm seeing the route still exists.

**Comment by johrstrom** [comment]
I fixed this in the PR listed there (the images anyhow). Just open more tickets or update this one if you see anything more.
