### ISSUE TITLE
The 'OSC/ood-documentation' repository doesn't contain the 'source/authentication/nsf-access.rst' path in 'develop'.  

### ISSUE THREAD

**Issue by jbasney** [OSC/ood-documentation#769]
When I click "Edit on GitHub" at https://osc.github.io/ood-documentation/latest/authentication/nsf-access.html I see the following error:

> The 'OSC/ood-documentation' repository doesn't contain the 'source/authentication/nsf-access.rst' path in 'develop'.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203857759536333) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks! Yea the `develop` branch is for 2.1 related stuff which isn't released yet so it's not 'public' in that sense.

`latest` is the public/current release branch, and we're more than happy to get any updates you may have!

https://github.com/OSC/ood-documentation/edit/latest/source/authentication/nsf-access.rst

**Comment by johrstrom** [comment]
Thanks for the updates. I believe the issue you've described I've captured in #770.
