### ISSUE TITLE
Explore using "subprojects" to reduce menu size

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-documentation#77]
It was mentioned that we should explore sub-projects as a way to reduce our left-hand navigation menu's size.

> I notice when I navigate between the subsections of add-custom-queue the navigation on the left disappears because on a new page you are scrolled to the top and you have to scroll down to see. The readthedocs theme I think supports "subprojects" https://docs.readthedocs.io/en/latest/faq.html#how-do-i-host-multiple-projects-on-one-cname (or that might just be the readthedocs site itself...). My guess is this would result in the left navigation being devoted entirely to that subproject, which could be "App Development" or even "Interactive App Development". This is outside the scope of this PR though, maybe worth opening another issue.

**Comment by ericfranz** [comment]
We might consider this later. Right now, the menu on the left can just get very large and that is fine.
