### ISSUE TITLE
SAML2.0/ADFS authentication instructions are incorrect

### ISSUE THREAD

**Issue by walidabualafia** [OSC/ood-documentation#861]
Packages:
- `httpd24-mod_auth_mellon`
- `https24-mod_ssl`

are unavailable in RHEL8 yum repos and streams. These packages are only `.el7`. Are there any updated instructions on how to integrate OnDemand with SAML2.0/ADFS on a RHEL8 host?

I can install the packages manually and unpack them, but RHEL does not recommend cross-version installations. This system will be in production, so I need it to be as reliable as possible, and therefore I'm avoiding cross-version installs.

Cheers,
Walid

**Comment by johrstrom** [comment]
The packages should have the same name - just without the `httpd24-` prefix. I've moved this ticket to our documentation repo where I can update for the same.

**Comment by walidabualafia** [comment]
Thanks, Jeff. I can confirm I installed the packages. Cheers.
