### ISSUE TITLE
Document Greedy `host_regex` (Moved from OOD repo)

### ISSUE THREAD

**Issue by Oglopf** [OSC/ood-documentation#883]
This is just a ticket to move a request about the docs to the correct location so we can implement the fix here.

The issue was originally posted here:
https://github.com/OSC/ondemand/issues/3130

And the following is a copy of the post from micket:

I spent some time debugging why some of my apps didn't work correctly, when I eventually discovered I had been neglectful when specifying my host_regex configuration. I had done something like

host_regex: "foo.*"

which will cause confusing issues, no error messages (from what I could find), but apps either didn't work, or just partially didn't work.
Example, the desktop app still worked fine, while a jupyter notebook will launch the browser just fine, but won't be able to connect to any python kernel.
Other fails to find most of it's linked material, leaving a typical white page and maybe a favicon.

While the examples do correctly show regex which correctly excludes /, I think it would help to make this requirement explicitly written in the docs, otherwise strange things will happen with the proxy'ing.

https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html?highlight=host_regex#configure-reverse-proxy

**Comment by Micket** [comment]
Thanks! Sorry for putting it in the wrong repo
