### ISSUE TITLE
Switch to Gitbook?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#98]
1. It offers the warning, tip, etc.: https://docs.gitbook.com/content-editing/rich-content
2. It supports custom domains (like docs.openondemand.org) and header links for higher level navigation
3. The left side hierarchical navigation looks
4. It supports multiple branches for different versions of Gitbook

I'm not sure about publishing every possible branch for testing purposes though. 

We should do an experiment to see if this is viable.

**Comment by MorganRodgers** [comment]
What do we gain by switching?

**Comment by ericfranz** [comment]
1. Not maintaining our own infrastructure to manage and build versions of documentation (though that is already built - and maybe we still need to do that for test branches?)
2. Easier and faster to write markdown than sphinx
3. Cleaner organization of pages (?) (though we could achieve same I guess with Sphinx)

**Comment by MorganRodgers** [comment]
Fair enough, I was just curious about the value added.

**Comment by ericfranz** [comment]
Looks like GitBook changed and is no longer repo based. We could just start using readthedocs.org instead of continuing to build our own... Or we could continue as is but start using markdown files where it makes sense too, since it supports both.
